os: osx
language: xamarin
solution: solution-name

mono:
  mdk: 4.6.2
  android: 7.0.2-42
  ios: 10.3.1.8

android:
  components:
    - build-tools-25.0.1
    - android-24
    - extra

osx_image: xcode8.2

install:
  - nuget restore solution-name.sln
  - xbuild /t:SignAndroidPackage /p:Configuration=Release Droid/solution-name.Droid.csproj
  - xbuild /p:Configuration="Release" /p:Platform="iPhone" /p:IpaPackageDir="$HOME/Builds" /t:Build solution-name.sln
